Second 2210 release with re-worked Settings
CoreMedia/coremedia-globallink-connect-integration pull request #50
Opened 2022-11-30 16:35 UTC by aprantl

2022-12-06 16:29 UTC, stefanpieper requested changes

2022-12-06 16:29 UTC, stefanpieper commented on CHANGELOG.md
> +  2. Move the existing GlobalLink settings into the global- and site-specific
State naming convention for settings document explicitly? In apps/studio-client/shared/js/gcc/src/GccWorkflowPlugin.ts it looks like the settings document's name is fixed.

Are these site-specific folders required in any case or just, if site-specific GlobalLink settings are used? Is the global settings folder required in any case as soon as the extension is active?

2022-12-06 16:29 UTC, stefanpieper commented on CHANGELOG.md
> +  them anymore by checking the system tab. In the future, you don't need to
"don't need to" -> "should not" (in order not to potentially expose sensitive data).

2022-12-06 16:29 UTC, stefanpieper commented on docs/administration.md
> +for some site. The Settings can be located in the following folders:
"or specifically for some site." -> "or specifically for some site. Site-specific settings override global settings except for `dayOffsetForDueDate`."

2022-12-06 16:29 UTC, stefanpieper commented on docs/administration.md
> +Be aware the `dayOffsetForDueDate` can only be configured in the global
"Be aware the" -> "Be aware that the"

2022-12-06 16:29 UTC, stefanpieper commented on docs/development.md
>  to the linked settings. To patch a homepage in server export you can use
Huh? "add [...] settings document to the linked settings"?

2022-12-06 16:29 UTC, stefanpieper commented on docs/development.md
> +  "\\#.*<linkedSettings>.*#a <link href=\"../../../../../../Settings/Options/Settings/Translation Services/GlobalLink.xml\" path=\"/Settings/Options/Settings/Translation Services/GlobalLink\"/>" \
"Huh?" again.

2022-12-06 17:22 UTC, aprantl commented on docs/release/manual-test-steps.md
> -    4. Document _GlobalLink_ is linked in homepage document of site you want to
You are welcome ;) It wasn't only search and replace.

2022-12-08 13:16 UTC, stefanpieper approved these changes

2022-12-08 16:10 UTC, merged